language: python
python:
    - 2.7
    - 3.4
    - 3.5
env:
    - DJANGO_VERSION=1.9.*
    - DJANGO_VERSION=1.8.*
install:
    - pip install -U pip
    - pip install Django=="$DJANGO_VERSION"
    - pip install coveralls
    - python setup.py install
script:
    coverage run --source=django_nvd3 -m unittest test_django_nvd3
after_success:
    coveralls
branches:
    only:
        - develop
