language: python
python:
    - 2.7
    - 3.4
    - 3.5
env:
    - DJANGO_VERSION=1.9.*
    - DJANGO_VERSION=1.8.*
install:
    - pip install -U pip
    - pip install Django=="$DJANGO_VERSION"
    - python setup.py install
script:
    - python setup.py test
branches:
    only:
        - develop
