language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
before_install:
    - pip install -U pip
    - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install 'Django<1.9'; fi
install:
    - python setup.py install
script:
    - python setup.py test
notifications:
    email: true
branches:
    only:
        - develop
